require("config.keys")
require("config.window")
require("config.general")
require("config.rooter")
require("config.lsp")
require("config.statusline")

require("plugins.theme")
require("plugins.neotree")
require("plugins.commentor")
require("plugins.copilot")
require("plugins.git")
require("plugins.fzf")
require("plugins.surround")
require("plugins.codecompanion")
require("plugins.mason")
require("plugins.autoformat")
require("plugins.treesitter")
